### ISSUE TITLE
Okib call wrecked

### ISSUE THREAD

**Issue by Archimonde666** [impossible-bosses/ibce-bots#11]
the gather completed (8) call did not occur for multiple times when going down to 7/8 and 8/8 again
restarting the gather with !noib and !okib retrieve did not fix the problem.
Removing manually and adding manually (with commands instead of reaction event listener) the 8th player wouldn't triggers the gather aswel

**Comment by jmrico01** [comment]
@Archimonde666 this reminds me we should probably add some logs to okib things, at least on gather, though tbh I would add them on every update (!okib and react) and print the full okib/noib lists. I also need to stop printing so much for lobbies haha

**Comment by Archimonde666** [comment]
I looked more deeply into it and the gather reset seems not to be implemented at all it just disapeared from the code U_u
Just need to code that again and it should work =))

**Comment by Archimonde666** [comment]
Fixed, it was indeed patio induced issue ^.^
