### ISSUE TITLE
Replace :okib: and :noib: reaction system on lobby display

### ISSUE THREAD

**Issue by Archimonde666** [impossible-bosses/ibce-bots#13]
Ppl find this confusing and so do i, i suggest replace this system with a new :notifyIB: emote that i'm gonna create for this purpose so it's more obvious

**Comment by Archimonde666** [comment]
Actually i think we should use the default notification bell of discord (snowflake = 792697144548392970)
For both the reaction and the embedded icon

**Comment by jmrico01** [comment]
ahh notification bell, of course. big brain Archi. will change this when I have some time

**Comment by jmrico01** [comment]
done
