### ISSUE TITLE
Post wc3stats game link when a replay is uploaded

### ISSUE THREAD

**Issue by jmrico01** [impossible-bosses/ibce-bots#21]
When the bot uploads a replay file, it should post a link to the uploaded game stats page.

Archi shared the response from a POST request, and it didn't seem to have the info required for this. I'll ask in the wc3stats Discord.

**Comment by Archimonde666** [comment]
Yeah i confirm no info into the replay POST reponse, that should be added by anders btw. Even with a deep look at the API, it doesnt look like i'm able to select a specific replay by anything that could be optained via this interface sadly :'(

**Comment by jmrico01** [comment]
> yes it should return the same format as api.wc3stats.com/replays/<id> so the id would be body.id

-Anders

@Archimonde666 might wanna double check this

**Comment by Archimonde666** [comment]
b'{"status":"OK","code":200,"queryTime":47.3706,"body":{"hash":"164308c69264a7c140cfda09264e8b77","name":"shaoh45","map":"Impossible.Bosses.v","variant":null,"flags":0,"file":"https:\\/\\/wc3stats.s3.amazonaws.com\\/replays\\/164308c69264a7c140cfda09264e8b77\\/Kiiskifish-shaoh45.w3g","size":3044286,"length":3247,"playedOn":1609954204,"ladder":"Public","season":"Season 1","keys":[],"processed":false,"uploads":[{"saver":"Kiiskifish","file":"https:\\/\\/wc3stats.s3.amazonaws.com\\/replays\\/164308c69264a7c140cfda09264e8b77\\/Kiiskifish-shaoh45.w3g","size":3044286,"timestamp":1610055470}],"data":===MAP DATA REMOVED FOR LISIBILITY===,"downloads":0,"isVoid":false,"overridable":true,**"id":82696**,"container":null,"_id":{"$oid":"5ff5f39d1e6f6e798eba330c"}}}'

**Comment by Archimonde666** [comment]
Ok i double checked that the field actually exists but the format is nonsense : almost every info stands before the whole replay data
but a few infomation is actually AFTER the big data
Should be able to do that easily then

**Comment by Archimonde666** [comment]
Done
