### ISSUE TITLE
PM when a lobby is created for "Recruiting & Pubs" role

### ISSUE THREAD

**Issue by jmrico01** [impossible-bosses/ibce-bots#25]
Requested by typical_methods
> hey patio, can you code bot to PM me when a game is hosted in #pub-games ? I keep missing them cause a dot appears on discord app, but I don't get the message over anything else
or PM my role - would make more sense

We can make the bot PM all users with the `Recruiting & Pubs` role when a lobby is first seen.

**Comment by jmrico01** [comment]
We added Triggs bot to the discord, which fills this niche for now. We probably won't implement this unless people are actually using this Triggs notify feature a lot.

**Comment by Archimonde666** [comment]
Well the point where it PM the recruiting & pubs role specifically i don't like it, typical wants it but is successor might not.
The only way to go is to "allow" someone to register for these PM as well as allowing him to unsubscribe for these, that's basically what's done with EU/NA/KR 
I feel like mentions is enough, i don't rly know why players wants PM it's highly invasive but w/e i guess it's quite easy to implement if other players asks

**Comment by jmrico01** [comment]
eh, I'm closing this one
