### ISSUE TITLE
Sync workspace for OKIB variables

### ISSUE THREAD

**Issue by jmrico01** [impossible-bosses/ibce-bots#41]
I think this is the last requirement to actually run the bot with multiple instances. Need to send and receive relevant OKIB workspace variables in `send_workspace` and `update_workspace` functions.

**Comment by Archimonde666** [comment]
Why do you need that ? :/ it's kinda hard to do first because we don't have evolved coms it's just a discord guild (we might get spotted and the bot account banned if discord spots massive and reccurring binary messages there) 
What kinds of variables are thoses ?

**Comment by jmrico01** [comment]
This is only for bot startup, so that any new instance receives all required global variables from the master instance. For example, currently we're sending the lobby list thru a few variables, and for OKIB I believe we need everything except the loaded emotes - list of okib/laterib/noib, active okib message ID, active okib channel, gatherer, etc...

This sync seems necessary for proper bot functioning after restart. It's not much work to add, I already figured out how to encode/decode any variable into a file to send for lobbies, and we shouldn't be restarting bots often, so the comms will be rare.

**Comment by jmrico01** [comment]
done with #42
