### ISSUE TITLE
Differentiate ENT gathers from Bnet Gathers

### ISSUE THREAD

**Issue by typical-methods** [impossible-bosses/ibce-bots#43]
Allow a bnet gather to be created so bnet players - for "pub-hosts" role specifically. Knowing who in the discord is interested - anyone can OKIB.

I had the following idea:

The player that starts the Gather would have the following multiple choice/parameter field: okib hosted on (BnetNA/BnetEU/BnetAsia) for (duration). 

When a player clicks on the okib button on the gather bot they would have an optional time limit field they could fill out. The format for the gatherbot could be changed to make it look more like a list. This time limit would be the total time a player has at the time to play. 

So the Final Product would look something like this:

------------------------------------------------------------------------------

Typical_Methods asks: IB hosted on Bnet NA in for playtime of 240 min. 

         Player Name ............Duration

 OKIB: Typical_Methods ..............................240 minutes 
  ......... Player 2 ................................... 
  ........Player 3 ....................................110 minutes
 NOIB:

------------------------------------------------------------------------------

**Comment by Archimonde666** [comment]
Duplicate from [](https://github.com/impossible-bosses/ibce-bots/issues/16)
https://github.com/impossible-bosses/ibce-bots/issues/16

**Comment by typical-methods** [comment]
Is not duplicate, in that 16 refers to notification of lobby - not gather bot.

**Comment by Archimonde666** [comment]
Alr my bad i though we talked about this in the lobby but apparently not, maybe it's in another issue i'll look

**Comment by Archimonde666** [comment]
reopened https://github.com/impossible-bosses/ibce-bots/issues/6
